giocatori = {
    "Abdulhamid": ['Roma', 'D', 5, 'SI'],
    "Abraham": ['Milan', 'A', 10, 'SI'],
    "Acerbi": ['Inter', 'D', 12, 'SI'],
    "Achour": ['Cagliari', 'A', 1, 'SI'],
    "Adams": ['Torino', 'A', 13, 'SI'],
    "Adli": ['Fiorentina', 'C', 11, 'SI'],
    "Adopo": ['Cagliari', 'C', 4, 'SI'],
    "Adzic": ['Juventus', 'C', 2, 'SI'],
    "Aebischer": ['Bologna', 'C', 8, 'SI'],
    "Ahanor": ['Genoa', 'D', 1, 'SI'],
    "Ajayi": ['Verona', 'A', 1, 'SI'],
    "Akpa-Akpro": ['Monza', 'C', 2, 'SI'],
    "Alberto Costa": ['Juventus', 'D', 6, 'SI'],
    "Alex Valle": ['Como', 'D', 6, 'SI'],
    "Almqvist": ['Parma', 'A', 8, 'SI'],
    "Amey": ['Bologna', 'D', 2, 'SI'],
    "Amin Sarr": ['Verona', 'A', 6, 'SI'],
    "Angelino": ['Roma', 'D', 17, 'SI'],
    "Anghele": ['Juventus', 'A', 1, 'SI'],
    "Anguissa": ['Napoli', 'C', 22, 'SI'],
    "Anjorin": ['Empoli', 'C', 9, 'SI'],
    "Arnautovic": ['Inter', 'A', 10, 'SI'],
    "Asllani": ['Inter', 'C', 9, 'SI'],
    "Assane Diao": ['Como', 'C', 11, 'SI'],
    "Atta": ['Udinese', 'C', 9, 'SI'],
    "Augello": ['Cagliari', 'D', 12, 'SI'],
    "Azon": ['Como', 'A', 3, 'SI'],
    "Bacci": ['Empoli', 'C', 1, 'SI'],
    "Badelj": ['Genoa', 'C', 9, 'SI'],
    "Bagnolini": ['Bologna', 'P', 3, 'SI'],
    "Baldanzi": ['Roma', 'C', 10, 'SI'],
    "Balogh": ['Parma', 'D', 8, 'SI'],
    "Balotelli": ['Genoa', 'A', 9, 'SI'],
    "Banda": ['Lecce', 'A', 7, 'SI'],
    "Bani": ['Genoa', 'D', 9, 'SI'],
    "Barella": ['Inter', 'C', 32, 'SI'],
    "Baroncelli": ['Fiorentina', 'D', 1, 'SI'],
    "Bartesaghi": ['Milan', 'D', 2, 'SI'],
    "Baschirotto": ['Lecce', 'D', 8, 'SI'],
    "Basic": ['Lazio', 'C', 2, 'SI'],
    "Bastoni": ['Inter', 'D', 24, 'SI'],
    "Baudouin": ['Venezia', 'D', 1, 'SI'],
    "Belahyane": ['Lazio', 'C', 7, 'SI'],
    "Bellanova": ['Atalanta', 'D', 18, 'SI'],
    "Beltran": ['Fiorentina', 'A', 13, 'SI'],
    "Benedyczak": ['Parma', 'A', 3, 'SI'],
    "Berardi A": ['Verona', 'P', 1, 'SI'],
    "Berenbruch": ['Inter', 'C', 1, 'SI'],
    "Berisha M": ['Lecce', 'C', 6, 'SI'],
    "Bernabe'": ['Parma', 'C', 10, 'SI'],
    "Bernede": ['Verona', 'C', 3, 'SI'],
    "Beukema": ['Bologna', 'D', 11, 'SI'],
    "Bianco A": ['Monza', 'C', 10, 'SI'],
    "Bijol": ['Udinese', 'D', 15, 'SI'],
    "Bilal Mazhar": ['Como', 'A', 1, 'SI'],
    "Billing": ['Napoli', 'C', 8, 'SI'],
    "Biraghi": ['Torino', 'D', 10, 'SI'],
    "Birindelli": ['Monza', 'D', 10, 'SI'],
    "Bisseck": ['Inter', 'D', 12, 'SI'],
    "Bjarkason": ['Venezia', 'C', 5, 'SI'],
    "Bondo": ['Milan', 'C', 8, 'SI'],
    "Bonny": ['Parma', 'A', 12, 'SI'],
    "Borna Sosa": ['Torino', 'D', 9, 'SI'],
    "Bove": ['Fiorentina', 'C', 9, 'SI'],
    "Bradaric D": ['Verona', 'D', 3, 'SI'],
    "Brancolini": ['Empoli', 'P', 1, 'SI'],
    "Braunoder": ['Como', 'C', 1, 'SI'],
    "Bremer": ['Juventus', 'D', 9, 'SI'],
    "Brenner": ['Udinese', 'A', 5, 'SI'],
    "Brescianini": ['Atalanta', 'C', 10, 'SI'],
    "Brorsson": ['Monza', 'D', 1, 'SI'],
    "Buongiorno": ['Napoli', 'D', 15, 'SI'],
    "Burnete": ['Lecce', 'A', 1, 'SI'],
    "Busio": ['Venezia', 'C', 9, 'SI'],
    "Butez": ['Como', 'P', 8, 'SI'],
    "Byar": ['Bologna', 'C', 2, 'SI'],
    "Cabal": ['Juventus', 'D', 8, 'SI'],
    "Cacace": ['Empoli', 'D', 10, 'SI'],
    "Calabria": ['Bologna', 'D', 10, 'SI'],
    "Caldirola": ['Monza', 'D', 2, 'SI'],
    "Calhanoglu": ['Inter', 'C', 29, 'SI'],
    "Calligaris": ['Inter', 'P', 1, 'SI'],
    "Camara D": ['Parma', 'C', 8, 'SI'],
    "Camarda": ['Milan', 'A', 3, 'SI'],
    "Cambiaghi": ['Bologna', 'A', 12, 'SI'],
    "Cambiaso": ['Juventus', 'D', 16, 'SI'],
    "Campaniello": ['Empoli', 'A', 1, 'SI'],
    "Cancellieri": ['Parma', 'A', 4, 'SI'],
    "Cande": ['Venezia', 'D', 4, 'SI'],
    "Caprari": ['Monza', 'A', 9, 'SI'],
    "Caprile": ['Cagliari', 'P', 11, 'SI'],
    "Caprini": ['Fiorentina', 'A', 1, 'SI'],
    "Caqueret": ['Como', 'C', 11, 'SI'],
    "Carboni A": ['Monza', 'D', 1, 'SI'],
    "Carboni F": ['Venezia', 'D', 3, 'SI'],
    "Carlos Augusto": ['Inter', 'D', 17, 'SI'],
    "Carnesecchi": ['Atalanta', 'P', 25, 'SI'],
    "Casadei": ['Torino', 'C', 12, 'SI'],
    "Casale": ['Bologna', 'D', 6, 'SI'],
    "Cassa": ['Atalanta', 'C', 1, 'SI'],
    "Castellanos": ['Lazio', 'A', 15, 'SI'],
    "Castro S": ['Bologna', 'A', 16, 'SI'],
    "Castrovilli": ['Monza', 'C', 7, 'SI'],
    "Cataldi": ['Fiorentina', 'C', 11, 'SI'],
    "Caviglia": ['Venezia', 'C', 18, 'SI'],
    "Celik": ['Roma', 'D', 7, 'SI'],
    "Charpentier": ['Parma', 'A', 7, 'SI'],
    "Ciocci": ['Cagliari', 'P', 1, 'SI'],
    "Circati": ['Parma', 'D', 4, 'SI'],
    "Cisse A": ['Verona', 'C', 1, 'SI'],
    "Ciurria": ['Monza', 'C', 10, 'SI'],
    "Coco S": ['Torino', 'D', 11, 'SI'],
    "Colombo": ['Empoli', 'A', 9, 'SI'],
    "Colombo L": ['Monza', 'C', 1, 'SI'],
    "Colombo M": ['Atalanta', 'C', 1, 'SI'],
    "Colpani": ['Fiorentina', 'C', 9, 'SI'],
    "Coman F": ['Cagliari', 'C', 6, 'SI'],
    "Comenencia": ['Juventus', 'C', 1, 'SI'],
    "Comuzzo": ['Fiorentina', 'D', 8, 'SI'],
    "Conceicao": ['Juventus', 'C', 17, 'SI'],
    "Conde": ['Venezia', 'C', 4, 'SI'],
    "Contini": ['Napoli', 'P', 1, 'SI'],
    "Coppola D": ['Verona', 'D', 7, 'SI'],
    "Corfitzen": ['Lecce', 'A', 1, 'SI'],
    "Cornet": ['Genoa', 'A', 8, 'SI'],
    "Correa": ['Inter', 'A', 8, 'SI'],
    "Corvi": ['Parma', 'P', 1, 'SI'],
    "Coubis": ['Milan', 'D', 2, 'SI'],
    "Coulibaly L": ['Lecce', 'C', 9, 'SI'],
    "Cristante": ['Roma', 'C', 12, 'SI'],
    "Crnigoj": ['Venezia', 'C', 2, 'SI'],
    "Cruz J": ['Verona', 'A', 1, 'SI'],
    "Cuadrado": ['Atalanta', 'D', 10, 'SI'],
    "Cuenca": ['Genoa', 'C', 1, 'SI'],
    "Cutrone": ['Como', 'A', 13, 'SI'],
    "D'ambrosio": ['Monza', 'D', 4, 'SI'],
    "Da Cunha": ['Como', 'C', 15, 'SI'],
    "Dallinga": ['Bologna', 'A', 10, 'SI'],
    "Daniliuc": ['Verona', 'D', 2, 'SI'],
    "Danilo Veiga": ['Lecce', 'D', 3, 'SI'],
    "Darmian": ['Inter', 'D', 9, 'SI'],
    "Davis": ['Udinese', 'A', 9, 'SI'],
    "Dawidowicz": ['Verona', 'D', 7, 'SI'],
    "De Gea": ['Fiorentina', 'P', 23, 'SI'],
    "De Ketelaere": ['Atalanta', 'C', 27, 'SI'],
    "De Marzi": ['Roma', 'P', 1, 'SI'],
    "De Nipoti": ['Atalanta', 'A', 1, 'SI'],
    "De Pieri": ['Inter', 'A', 1, 'SI'],
    "De Roon": ['Atalanta', 'C', 19, 'SI'],
    "De Sciglio": ['Empoli', 'D', 2, 'SI'],
    "De Silvestri": ['Bologna', 'D', 6, 'SI'],
    "De Vrij": ['Inter', 'D', 10, 'SI'],
    "De Winter": ['Genoa', 'D', 10, 'SI'],
    "Deiola": ['Cagliari', 'C', 5, 'SI'],
    "Del Prato": ['Parma', 'D', 10, 'SI'],
    "Dele Alli": ['Como', 'C', 1, 'SI'],
    "Dele Bashiru": ['Lazio', 'C', 12, 'SI'],
    "Delle Monache": ['Lecce', 'A', 1, 'SI'],
    "Dembele A": ['Torino', 'D', 2, 'SI'],
    "Di Gennaro R": ['Inter', 'P', 2, 'SI'],
    "Di Gregorio": ['Juventus', 'P', 24, 'SI'],
    "Di Lorenzo": ['Napoli', 'D', 21, 'SI'],
    "Di Tommaso": ['Lazio', 'C', 1, 'SI'],
    "Dia": ['Lazio', 'A', 16, 'SI'],
    "Dimarco": ['Inter', 'D', 21, 'SI'],
    "Djimsiti": ['Atalanta', 'D', 13, 'SI'],
    "Djuric": ['Parma', 'A', 9, 'SI'],
    "Dodo D": ['Fiorentina', 'D', 13, 'SI'],
    "Dominguez B": ['Bologna', 'C', 14, 'SI'],
    "Donnarumma A": ['Torino', 'P', 1, 'SI'],
    "Dossena A": ['Como', 'D', 10, 'SI'],
    "Douglas Luiz": ['Juventus', 'C', 9, 'SI'],
    "Doumbia I": ['Venezia', 'C', 7, 'SI'],
    "Douvikas": ['Como', 'A', 9, 'SI'],
    "Dovbyk": ['Roma', 'A', 23, 'SI'],
    "Duda": ['Verona', 'C', 12, 'SI'],
    "Dumfries": ['Inter', 'D', 21, 'SI'],
    "Duncan": ['Venezia', 'C', 10, 'SI'],
    "Dybala": ['Roma', 'A', 27, 'SI'],
    "Ebuehi": ['Empoli', 'D', 4, 'SI'],
    "Ederson J": ['Atalanta', 'C', 18, 'SI'],
    "Ehizibue": ['Udinese', 'D', 10, 'SI'],
    "Ekhator": ['Genoa', 'A', 7, 'SI'],
    "Ekkelenkamp": ['Udinese', 'C', 14, 'SI'],
    "Ekuban": ['Genoa', 'A', 9, 'SI'],
    "El Azzouzi": ['Bologna', 'C', 5, 'SI'],
    "El Haddad": ['Venezia', 'C', 1, 'SI'],
    "El Shaarawy": ['Roma', 'A', 13, 'SI'],
    "Eletu": ['Milan', 'C', 2, 'SI'],
    "Ellertsson": ['Venezia', 'C', 10, 'SI'],
    "Elmas": ['Torino', 'C', 15, 'SI'],
    "Emerson Royal": ['Milan', 'D', 9, 'SI'],
    "Engelhardt": ['Como', 'C', 8, 'SI'],
    "Erlic": ['Bologna', 'D', 8, 'SI'],
    "Esposito S": ['Empoli', 'A', 13, 'SI'],
    "Estevez": ['Parma', 'C', 2, 'SI'],
    "Fabbian": ['Bologna', 'C', 12, 'SI'],
    "Fadera": ['Como', 'A', 10, 'SI'],
    "Fagioli": ['Fiorentina', 'C', 12, 'SI'],
    "Falcone": ['Lecce', 'P', 21, 'SI'],
    "Faraoni": ['Verona', 'D', 6, 'SI'],
    "Faticanti": ['Juventus', 'C', 1, 'SI'],
    "Fazzini": ['Empoli', 'C', 9, 'SI'],
    "Felici": ['Cagliari', 'C', 8, 'SI'],
    "Felipe Jack": ['Como', 'D', 1, 'SI'],
    "Ferguson": ['Bologna', 'C', 12, 'SI'],
    "Fila": ['Venezia', 'A', 6, 'SI'],
    "Florenzi": ['Milan', 'D', 5, 'SI'],
    "Fofana Y": ['Milan', 'C', 12, 'SI'],
    "Folorunsho": ['Fiorentina', 'C', 8, 'SI'],
    "Forson": ['Monza', 'C', 2, 'SI'],
    "Frattesi": ['Inter', 'C', 16, 'SI'],
    "Frendrup": ['Genoa', 'C', 15, 'SI'],
    "Frese": ['Verona', 'D', 2, 'SI'],
    "Freuler": ['Bologna', 'C', 15, 'SI'],
    "Fruchtl": ['Lecce', 'P', 1, 'SI'],
    "Furlanetto": ['Lazio', 'P', 1, 'SI'],
    "Gabbia": ['Milan', 'D', 8, 'SI'],
    "Gabrielloni": ['Como', 'A', 6, 'SI'],
    "Gaetano": ['Cagliari', 'C', 9, 'SI'],
    "Gagliardini": ['Monza', 'C', 5, 'SI'],
    "Gallo": ['Lecce', 'D', 8, 'SI'],
    "Ganvoula": ['Monza', 'A', 6, 'SI'],
    "Gaspar K": ['Lecce', 'D', 9, 'SI'],
    "Gatti": ['Juventus', 'D', 13, 'SI'],
    "Ghilardi": ['Verona', 'D', 5, 'SI'],
    "Giannetti L": ['Udinese', 'D', 4, 'SI'],
    "Gigot": ['Lazio', 'D', 9, 'SI'],
    "Gila": ['Lazio', 'D', 10, 'SI'],
    "Gilmour": ['Napoli', 'C', 8, 'SI'],
    "Gimenez S": ['Milan', 'A', 19, 'SI'],
    "Gineitis": ['Torino', 'C', 11, 'SI'],
    "Goglichidze": ['Empoli', 'D', 4, 'SI'],
    "Goldaniga": ['Como', 'D', 7, 'SI'],
    "Gollini": ['Roma', 'P', 9, 'SI'],
    "Gonzalez J": ['Lecce', 'C', 1, 'SI'],
    "Gonzalez N": ['Juventus', 'A', 9, 'SI'],
    "Gosens": ['Fiorentina', 'D', 18, 'SI'],
    "Gourna Douath": ['Roma', 'C', 5, 'SI'],
    "Grandi": ['Venezia', 'P', 1, 'SI'],
    "Grassi": ['Empoli', 'C', 6, 'SI'],
    "Gudmundsson": ['Fiorentina', 'A', 18, 'SI'],
    "Guendouzi": ['Lazio', 'C', 18, 'SI'],
    "Guessand": ['Udinese', 'D', 1, 'SI'],
    "Guilbert": ['Lecce', 'D', 6, 'SI'],
    "Gyasi": ['Empoli', 'C', 8, 'SI'],
    "Gytkjaer": ['Venezia', 'A', 5, 'SI'],
    "Haas": ['Empoli', 'C', 5, 'SI'],
    "Hainaut": ['Parma', 'C', 4, 'SI'],
    "Haj Mohamed": ['Parma', 'A', 6, 'SI'],
    "Han": ['Udinese', 'C', 1, 'SI'],
    "Haps": ['Venezia', 'D', 2, 'SI'],
    "Harroui": ['Verona', 'C', 9, 'SI'],
    "Hasa": ['Napoli', 'C', 1, 'SI'],
    "Helgason": ['Lecce', 'C', 8, 'SI'],
    "Henderson": ['Empoli', 'C', 6, 'SI'],
    "Hernandez T": ['Milan', 'D', 17, 'SI'],
    "Hernani": ['Parma', 'C', 10, 'SI'],
    "Hien": ['Atalanta', 'D', 10, 'SI'],
    "Holm": ['Bologna', 'D', 9, 'SI'],
    "Hummels": ['Roma', 'D', 10, 'SI'],
    "Hysaj": ['Lazio', 'D', 9, 'SI'],
    "Ibrahimovic A": ['Lazio', 'C', 3, 'SI'],
    "Idzes": ['Venezia', 'D', 11, 'SI'],
    "Iker Bravo": ['Udinese', 'A', 9, 'SI'],
    "Ikone": ['Como', 'C', 11, 'SI'],
    "Ilic": ['Torino', 'C', 9, 'SI'],
    "Ilkhan": ['Torino', 'C', 1, 'SI'],
    "Iovine": ['Como', 'C', 2, 'SI'],
    "Isaksen": ['Lazio', 'C', 15, 'SI'],
    "Ismajli": ['Empoli', 'D', 10, 'SI'],
    "Izzo": ['Monza', 'D', 9, 'SI'],
    "Jankto": ['Cagliari', 'C', 4, 'SI'],
    "Jean": ['Lecce', 'D', 3, 'SI'],
    "Jimenez A": ['Milan', 'D', 5, 'SI'],
    "Joao Felix": ['Milan', 'A', 17, 'SI'],
    "Joronen": ['Venezia', 'P', 8, 'SI'],
    "Jovic": ['Milan', 'A', 9, 'SI'],
    "Juan Jesus": ['Napoli', 'D', 7, 'SI'],
    "Kaba": ['Lecce', 'C', 3, 'SI'],
    "Kabasele": ['Udinese', 'D', 6, 'SI'],
    "Kalulu": ['Juventus', 'D', 9, 'SI'],
    "Kamara": ['Udinese', 'D', 11, 'SI'],
    "Karamoh": ['Torino', 'A', 6, 'SI'],
    "Karlsson": ['Lecce', 'C', 6, 'SI'],
    "Karlstrom": ['Udinese', 'C', 11, 'SI'],
    "Kasa": ['Genoa', 'C', 1, 'SI'],
    "Kastanos": ['Verona', 'C', 9, 'SI'],
    "Kean": ['Fiorentina', 'A', 21, 'SI'],
    "Keita B": ['Monza', 'A', 8, 'SI'],
    "Kelly": ['Juventus', 'D', 3, 'SI'],
    "Kempf": ['Como', 'D', 8, 'SI'],
    "Kike Perez": ['Venezia', 'C', 7, 'SI'],
    "Kolasinac": ['Atalanta', 'D', 13, 'SI'],
    "Kolo Muani": ['Juventus', 'A', 18, 'SI'],
    "Konate I": ['Empoli', 'A', 2, 'SI'],
    "Koopmeiners": ['Juventus', 'C', 27, 'SI'],
    "Kossounou": ['Atalanta', 'D', 9, 'SI'],
    "Kouame": ['Empoli', 'A', 6, 'SI'],
    "Kovalenko": ['Empoli', 'C', 2, 'SI'],
    "Kowalski": ['Parma', 'A', 2, 'SI'],
    "Kristensen T": ['Udinese', 'D', 3, 'SI'],
    "Krstovic": ['Lecce', 'A', 16, 'SI'],
    "Kyriakopoulos": ['Monza', 'D', 8, 'SI'],
    "Lambourde": ['Verona', 'A', 4, 'SI'],
    "Lazaro": ['Torino', 'D', 14, 'SI'],
    "Lazovic": ['Verona', 'C', 8, 'SI'],
    "Lazzari M": ['Lazio', 'D', 6, 'SI'],
    "Leali": ['Genoa', 'P', 13, 'SI'],
    "Leao": ['Milan', 'A', 31, 'SI'],
    "Lekovic": ['Monza', 'D', 1, 'SI'],
    "Leoni": ['Parma', 'D', 2, 'SI'],
    "Liberali": ['Milan', 'A', 2, 'SI'],
    "Linetty": ['Torino', 'C', 9, 'SI'],
    "Livramento": ['Verona', 'A', 7, 'SI'],
    "Lobotka": ['Napoli', 'C', 12, 'SI'],
    "Locatelli M": ['Juventus', 'C', 11, 'SI'],
    "Loftus-Cheek": ['Milan', 'C', 11, 'SI'],
    "Lookman": ['Atalanta', 'A', 31, 'SI'],
    "Lovik": ['Parma', 'D', 3, 'SI'],
    "Lovric": ['Udinese', 'C', 18, 'SI'],
    "Luan Patrick": ['Verona', 'D', 1, 'SI'],
    "Lucca": ['Udinese', 'A', 22, 'SI'],
    "Lucumi": ['Bologna', 'D', 10, 'SI'],
    "Lukaku R": ['Napoli', 'A', 39, 'SI'],
    "Luperto": ['Cagliari', 'D', 10, 'SI'],
    "Luvumbo": ['Cagliari', 'A', 9, 'SI'],
    "Lykogiannis": ['Bologna', 'D', 11, 'SI'],
    "Maignan": ['Milan', 'P', 23, 'SI'],
    "Makoumbou": ['Cagliari', 'C', 7, 'SI'],
    "Maldini D": ['Atalanta', 'C', 10, 'SI'],
    "Maleh": ['Empoli', 'C', 9, 'SI'],
    "Malinovskyi": ['Genoa', 'C', 11, 'SI'],
    "Man": ['Parma', 'A', 13, 'SI'],
    "Mancini": ['Roma', 'D', 15, 'SI'],
    "Mancini T": ['Juventus', 'A', 1, 'SI'],
    "Mandas": ['Lazio', 'P', 2, 'SI'],
    "Mandela Keita": ['Parma', 'C', 4, 'SI'],
    "Mandragora": ['Fiorentina', 'C', 12, 'SI'],
    "Mannini M": ['Roma', 'C', 1, 'SI'],
    "Manu Kone": ['Roma', 'C', 14, 'SI'],
    "Manzoni A": ['Atalanta', 'C', 1, 'SI'],
    "Marcandalli": ['Venezia', 'D', 1, 'SI'],
    "Marchwinski": ['Lecce', 'C', 3, 'SI'],
    "Marcone": ['Parma', 'P', 1, 'SI'],
    "Mari": ['Fiorentina', 'D', 8, 'SI'],
    "Marianucci": ['Empoli', 'D', 1, 'SI'],
    "Maric": ['Venezia', 'A', 1, 'SI'],
    "Marin R": ['Cagliari', 'C', 10, 'SI'],
    "Maripan": ['Torino', 'D', 12, 'SI'],
    "Marras T": ['Monza', 'C', 1, 'SI'],
    "Martin": ['Genoa', 'D', 15, 'SI'],
    "Martinelli T": ['Fiorentina', 'P', 1, 'SI'],
    "Martinez J": ['Inter', 'P', 5, 'SI'],
    "Martinez L": ['Inter', 'A', 42, 'SI'],
    "Martins K": ['Monza', 'C', 4, 'SI'],
    "Marusic": ['Lazio', 'D', 12, 'SI'],
    "Masina": ['Torino', 'D', 10, 'SI'],
    "Masini": ['Genoa', 'C', 8, 'SI'],
    "Mathias Olivera": ['Napoli', 'D', 9, 'SI'],
    "Matturro": ['Genoa', 'D', 3, 'SI'],
    "Mazza": ['Monza', 'P', 1, 'SI'],
    "Mazzocchi": ['Napoli', 'D', 4, 'SI'],
    "Mbangula": ['Juventus', 'A', 10, 'SI'],
    "McKennie": ['Juventus', 'C', 9, 'SI'],
    "McTominay": ['Napoli', 'C', 27, 'SI'],
    "Meret": ['Napoli', 'P', 25, 'SI'],
    "Messias": ['Genoa', 'C', 9, 'SI'],
    "Mihaila": ['Parma', 'A', 9, 'SI'],
    "Milani": ['Lazio', 'D', 1, 'SI'],
    "Milik": ['Juventus', 'A', 8, 'SI'],
    "Milinkovic-Savic V": ['Torino', 'P', 25, 'SI'],
    "Mina": ['Cagliari', 'D', 10, 'SI'],
    "Miranda J": ['Bologna', 'D', 15, 'SI'],
    "Miretti": ['Genoa', 'C', 12, 'SI'],
    "Mkhitaryan": ['Inter', 'C', 19, 'SI'],
    "Montipo'": ['Verona', 'P', 16, 'SI'],
    "Moreno A": ['Como', 'D', 9, 'SI'],
    "Moreno M": ['Fiorentina', 'D', 1, 'SI'],
    "Morente": ['Lecce', 'A', 6, 'SI'],
    "Moro N": ['Bologna', 'C', 9, 'SI'],
    "Mosquera": ['Verona', 'A', 8, 'SI'],
    "Mota": ['Monza', 'A', 8, 'SI'],
    "Muhameti": ['Atalanta', 'C', 1, 'SI'],
    "Munoz": ['Lazio', 'C', 1, 'SI'],
    "Musah": ['Milan', 'C', 8, 'SI'],
    "Mutandwa": ['Cagliari', 'A', 2, 'SI'],
    "N'Dri": ['Lecce', 'A', 2, 'SI'],
    "Napolitano": ['Lazio', 'C', 1, 'SI'],
    "Nava": ['Milan', 'P', 3, 'SI'],
    "Ndicka": ['Roma', 'D', 15, 'SI'],
    "Ndour": ['Fiorentina', 'C', 6, 'SI'],
    "Ndoye": ['Bologna', 'C', 20, 'SI'],
    "Nelsson": ['Roma', 'D', 7, 'SI'],
    "Neres": ['Napoli', 'A', 19, 'SI'],
    "Ngonge": ['Napoli', 'A', 8, 'SI'],
    "Niasse": ['Verona', 'C', 2, 'SI'],
    "Nico Paz": ['Como', 'C', 21, 'SI'],
    "Njie": ['Torino', 'C', 7, 'SI'],
    "Norton-Cuffy": ['Genoa', 'D', 1, 'SI'],
    "Noslin": ['Lazio', 'A', 12, 'SI'],
    "Nuno Tavares": ['Lazio', 'D', 11, 'SI'],
    "Nwachukwu": ['Udinese', 'D', 1, 'SI'],
    "Nwanege": ['Verona', 'D', 1, 'SI'],
    "Obert": ['Cagliari', 'D', 9, 'SI'],
    "Odgaard": ['Bologna', 'A', 15, 'SI'],
    "Okafor": ['Napoli', 'A', 10, 'SI'],
    "Okou": ['Verona', 'D', 3, 'SI'],
    "Okoye": ['Udinese', 'P', 10, 'SI'],
    "Omoregbe": ['Milan', 'A', 1, 'SI'],
    "Onana J": ['Genoa', 'C', 3, 'SI'],
    "Ondrejka": ['Parma', 'C', 4, 'SI'],
    "Origi": ['Milan', 'A', 2, 'SI'],
    "Oristanio": ['Venezia', 'C', 13, 'SI'],
    "Orsolini": ['Bologna', 'C', 30, 'SI'],
    "Osorio": ['Parma', 'D', 1, 'SI'],
    "Otoa": ['Genoa', 'D', 1, 'SI'],
    "Oyegoke": ['Verona', 'D', 1, 'SI'],
    "Padelli": ['Udinese', 'P', 2, 'SI'],
    "Pafundi": ['Udinese', 'C', 1, 'SI'],
    "Palacios": ['Monza', 'D', 1, 'SI'],
    "Paleari": ['Torino', 'P', 2, 'SI'],
    "Palestra": ['Atalanta', 'C', 4, 'SI'],
    "Palomino": ['Cagliari', 'D', 5, 'SI'],
    "Papadopoulos": ['Juventus', 'C', 1, 'SI'],
    "Paredes": ['Roma', 'C', 12, 'SI'],
    "Parisi F": ['Fiorentina', 'D', 6, 'SI'],
    "Pasalic": ['Atalanta', 'C', 14, 'SI'],
    "Patric": ['Lazio', 'D', 5, 'SI'],
    "Pavard": ['Inter', 'D', 11, 'SI'],
    "Pavlovic S": ['Milan', 'D', 10, 'SI'],
    "Pavoletti": ['Cagliari', 'A', 7, 'SI'],
    "Payero": ['Udinese', 'C', 10, 'SI'],
    "Pedersen": ['Torino', 'D', 2, 'SI'],
    "Pedro Felipe": ['Juventus', 'D', 1, 'SI'],
    "Pedro R": ['Lazio', 'A', 11, 'SI'],
    "Pedrola": ['Bologna', 'C', 2, 'SI'],
    "Pejicic": ['Udinese', 'C', 1, 'SI'],
    "Pellegri": ['Empoli', 'A', 7, 'SI'],
    "Pellegrini": ['Roma', 'C', 9, 'SI'],
    "Pellegrini Lu": ['Lazio', 'D', 9, 'SI'],
    "Pellegrino Ma": ['Parma', 'A', 4, 'SI'],
    "Pereira P": ['Monza', 'D', 3, 'SI'],
    "Perez A": ['Inter', 'D', 1, 'SI'],
    "Perilli": ['Verona', 'P', 1, 'SI'],
    "Perin": ['Juventus', 'P', 6, 'SI'],
    "Perrone": ['Como', 'C', 8, 'SI'],
    "Pessina": ['Monza', 'C', 9, 'SI'],
    "Petagna": ['Monza', 'A', 3, 'SI'],
    "Pezzella": ['Empoli', 'D', 10, 'SI'],
    "Piana": ['Udinese', 'P', 1, 'SI'],
    "Piccoli": ['Cagliari', 'A', 11, 'SI'],
    "Pierotti": ['Lecce', 'A', 5, 'SI'],
    "Pierret": ['Lecce', 'C', 2, 'SI'],
    "Pinamonti": ['Genoa', 'A', 16, 'SI'],
    "Pinsoglio": ['Juventus', 'P', 2, 'SI'],
    "Pisano M": ['Como', 'A', 1, 'SI'],
    "Pisilli": ['Roma', 'C', 10, 'SI'],
    "Pizarro D": ['Udinese', 'A', 1, 'SI'],
    "Pizzignacco": ['Monza', 'P', 6, 'SI'],
    "Pobega": ['Bologna', 'C', 12, 'SI'],
    "Politano": ['Napoli', 'A', 20, 'SI'],
    "Pongracic": ['Fiorentina', 'D', 7, 'SI'],
    "Popovic": ['Napoli', 'C', 1, 'SI'],
    "Popovic A": ['Verona', 'D', 1, 'SI'],
    "Posch": ['Atalanta', 'D', 9, 'SI'],
    "Prati": ['Cagliari', 'C', 3, 'SI'],
    "Provedel": ['Lazio', 'P', 19, 'SI'],
    "Provstgaard": ['Lazio', 'D', 1, 'SI'],
    "Pugno": ['Juventus', 'A', 1, 'SI'],
    "Pulisic": ['Milan', 'C', 35, 'SI'],
    "Radu I": ['Venezia', 'P', 10, 'SI'],
    "Rafa Marin": ['Napoli', 'D', 7, 'SI'],
    "Rafia": ['Lecce', 'C', 4, 'SI'],
    "Ramadani": ['Lecce', 'C', 9, 'SI'],
    "Ranieri": ['Fiorentina', 'D', 11, 'SI'],
    "Raspadori": ['Napoli', 'A', 10, 'SI'],
    "Ravaglia F": ['Bologna', 'P', 8, 'SI'],
    "Razi": ['Como', 'C', 1, 'SI'],
    "Rebic": ['Lecce', 'A', 8, 'SI'],
    "Reijnders": ['Milan', 'C', 27, 'SI'],
    "Reina": ['Como', 'P', 6, 'SI'],
    "Renato Marin": ['Roma', 'P', 1, 'SI'],
    "Renato Veiga": ['Juventus', 'D', 5, 'SI'],
    "Rensch": ['Roma', 'D', 9, 'SI'],
    "Retegui": ['Atalanta', 'A', 28, 'SI'],
    "Ricci S": ['Torino', 'C', 16, 'SI'],
    "Richardson": ['Fiorentina', 'C', 8, 'SI'],
    "Romagnoli A": ['Lazio', 'D', 10, 'SI'],
    "Rossi F": ['Atalanta', 'P', 2, 'SI'],
    "Rouhi": ['Juventus', 'D', 2, 'SI'],
    "Rovella": ['Lazio', 'C', 12, 'SI'],
    "Rrahmani": ['Napoli', 'D', 15, 'SI'],
    "Rubino T": ['Fiorentina', 'C', 1, 'SI'],
    "Ruggeri": ['Atalanta', 'D', 9, 'SI'],
    "Rui Modesto": ['Udinese', 'D', 6, 'SI'],
    "Rui Patricio": ['Atalanta', 'P', 4, 'SI'],
    "Russo L": ['Torino', 'C', 1, 'SI'],
    "Sabelli": ['Genoa', 'D', 10, 'SI'],
    "Saelemaekers": ['Roma', 'C', 20, 'SI'],
    "Sagrado": ['Venezia', 'D', 1, 'SI'],
    "Sala M": ['Lecce', 'D', 1, 'SI'],
    "Salah Eddine": ['Roma', 'D', 7, 'SI'],
    "Salama": ['Torino', 'A', 3, 'SI'],
    "Samardzic": ['Atalanta', 'C', 12, 'SI'],
    "Sambia": ['Empoli', 'D', 4, 'SI'],
    "Samooja": ['Lecce', 'P', 1, 'SI'],
    "Sanabria": ['Torino', 'A', 10, 'SI'],
    "Sanchez": ['Udinese', 'A', 9, 'SI'],
    "Sangare'": ['Roma', 'D', 1, 'SI'],
    "Sansone N": ['Lecce', 'A', 3, 'SI'],
    "Sava": ['Udinese', 'P', 9, 'SI'],
    "Savona": ['Juventus', 'D', 9, 'SI'],
    "Savva": ['Torino', 'A', 1, 'SI'],
    "Sazonov": ['Empoli', 'D', 2, 'SI'],
    "Scalvini": ['Atalanta', 'D', 5, 'SI'],
    "Scamacca": ['Atalanta', 'A', 13, 'SI'],
    "Schingtienne": ['Venezia', 'D', 3, 'SI'],
    "Schuurs": ['Torino', 'D', 7, 'SI'],
    "Scott": ['Lecce', 'D', 1, 'SI'],
    "Scuffet": ['Napoli', 'P', 9, 'SI'],
    "Seghetti": ['Empoli', 'P', 1, 'SI'],
    "Sensi": ['Monza', 'C', 8, 'SI'],
    "Serdar": ['Verona', 'C', 7, 'SI'],
    "Sergi Roberto": ['Como', 'C', 9, 'SI'],
    "Sherri": ['Cagliari', 'P', 4, 'SI'],
    "Shomurodov": ['Roma', 'A', 10, 'SI'],
    "Sia": ['Milan', 'A', 2, 'SI'],
    "Siegrist": ['Genoa', 'P', 1, 'SI'],
    "Silvestri": ['Empoli', 'P', 2, 'SI'],
    "Simeone": ['Napoli', 'A', 8, 'SI'],
    "Skorupski": ['Bologna', 'P', 20, 'SI'],
    "Slotsager": ['Verona', 'D', 1, 'SI'],
    "Smolcic": ['Como', 'D', 2, 'SI'],
    "Sodero": ['Atalanta', 'C', 1, 'SI'],
    "Sohm": ['Parma', 'C', 11, 'SI'],
    "Solbakken": ['Empoli', 'A', 1, 'SI'],
    "Solet": ['Udinese', 'D', 9, 'SI'],
    "Sommariva": ['Genoa', 'P', 1, 'SI'],
    "Sommer": ['Inter', 'P', 23, 'SI'],
    "Soppy": ['Atalanta', 'D', 1, 'SI'],
    "Sottil": ['Milan', 'C', 9, 'SI'],
    "Soule": ['Roma', 'C', 17, 'SI'],
    "Spinazzola": ['Napoli', 'D', 11, 'SI'],
    "Sportiello": ['Milan', 'P', 3, 'SI'],
    "Stankovic F": ['Venezia', 'P', 9, 'SI'],
    "Strefezza": ['Como', 'C', 19, 'SI'],
    "Sulejmani": ['Lazio', 'A', 1, 'SI'],
    "Sulemana": ['Atalanta', 'C', 2, 'SI'],
    "Suslov": ['Verona', 'C', 11, 'SI'],
    "Suzuki": ['Parma', 'P', 15, 'SI'],
    "Sverko": ['Venezia', 'D', 5, 'SI'],
    "Svilar": ['Roma', 'P', 25, 'SI'],
    "Svoboda": ['Venezia', 'D', 6, 'SI'],
    "Tameze": ['Torino', 'C', 9, 'SI'],
    "Taremi": ['Inter', 'A', 9, 'SI'],
    "Tchaouna": ['Lazio', 'A', 8, 'SI'],
    "Tchatchoua": ['Verona', 'D', 10, 'SI'],
    "Tengstedt": ['Verona', 'A', 10, 'SI'],
    "Terracciano": ['Fiorentina', 'P', 9, 'SI'],
    "Terracciano F": ['Milan', 'D', 4, 'SI'],
    "Thauvin": ['Udinese', 'A', 18, 'SI'],
    "Thiaw": ['Milan', 'D', 9, 'SI'],
    "Thorsby": ['Genoa', 'C', 9, 'SI'],
    "Thuram": ['Inter', 'A', 39, 'SI'],
    "Thuram K": ['Juventus', 'C', 20, 'SI'],
    "Tiago Gabriel": ['Lecce', 'D', 2, 'SI'],
    "Toloi": ['Atalanta', 'D', 5, 'SI'],
    "Tomczyk": ['Bologna', 'C', 1, 'SI'],
    "Tomori": ['Milan', 'D', 9, 'SI'],
    "Torriani": ['Milan', 'P', 3, 'SI'],
    "Tosto L": ['Empoli', 'D', 1, 'SI'],
    "Toure I": ['Udinese', 'D', 4, 'SI'],
    "Traore C": ['Milan', 'A', 2, 'SI'],
    "Turati": ['Monza', 'P', 20, 'SI'],
    "Urbanski": ['Monza', 'C', 9, 'SI'],
    "Valenti": ['Parma', 'D', 7, 'SI'],
    "Valentini N": ['Verona', 'D', 2, 'SI'],
    "Valeri": ['Parma', 'D', 12, 'SI'],
    "Van der Brempt": ['Como', 'D', 10, 'SI'],
    "Vasquez": ['Genoa', 'D', 17, 'SI'],
    "Vasquez D": ['Empoli', 'P', 9, 'SI'],
    "Vavassori": ['Atalanta', 'A', 1, 'SI'],
    "Vecino": ['Lazio', 'C', 10, 'SI'],
    "Venturino": ['Genoa', 'A', 2, 'SI'],
    "Vignato S": ['Monza', 'C', 4, 'SI'],
    "Vigorito": ['Como', 'P', 2, 'SI'],
    "Viola": ['Cagliari', 'C', 11, 'SI'],
    "Viti": ['Empoli', 'D', 9, 'SI'],
    "Vitinha": ['Genoa', 'A', 8, 'SI'],
    "Vlahovic": ['Juventus', 'A', 18, 'SI'],
    "Vlahovic V": ['Atalanta', 'A', 2, 'SI'],
    "Vlasic": ['Torino', 'C', 18, 'SI'],
    "Vogliacco": ['Parma', 'D', 4, 'SI'],
    "Vojvoda": ['Como', 'D', 8, 'SI'],
    "Vos": ['Milan', 'C', 2, 'SI'],
    "Walker": ['Milan', 'D', 10, 'SI'],
    "Walukiewicz": ['Torino', 'D', 5, 'SI'],
    "Weah": ['Juventus', 'D', 13, 'SI'],
    "Yeboah J": ['Venezia', 'C', 6, 'SI'],
    "Yildiz": ['Juventus', 'A', 19, 'SI'],
    "Yilmaz": ['Lecce', 'C', 1, 'SI'],
    "Zaccagni": ['Lazio', 'C', 30, 'SI'],
    "Zalewski": ['Inter', 'D', 9, 'SI'],
    "Zampano": ['Venezia', 'D', 6, 'SI'],
    "Zaniolo": ['Fiorentina', 'C', 12, 'SI'],
    "Zanoli": ['Genoa', 'D', 9, 'SI'],
    "Zapata D": ['Torino', 'A', 10, 'SI'],
    "Zappa": ['Cagliari', 'D', 9, 'SI'],
    "Zappacosta": ['Atalanta', 'D', 14, 'SI'],
    "Zarraga": ['Udinese', 'C', 4, 'SI'],
    "Zemura": ['Udinese', 'D', 9, 'SI'],
    "Zerbin": ['Venezia', 'A', 5, 'SI'],
    "Zeroli": ['Monza', 'C', 2, 'SI'],
    "Zielinski": ['Inter', 'C', 9, 'SI'],
    "Zortea": ['Cagliari', 'D', 15, 'SI'],
    "Zurkowski": ['Empoli', 'C', 9, 'SI'],
}
